add missing SET PSE SSL PURPOSE REMOTE SOURCE;
This fixes the problem:
Error: (dberror) [2]: general error: Unable to determine SSL connection mode; Certificate is required